import {
  MarketplaceFeeRule,
  SellerProgramRule,
  TaxRule,
  Pph22Rule,
} from '../../types/rules.ts';

/**
 * ASIS SELLER - Official Rules Single Source of Truth
 * 
 * Traceability:
 * - Shopee rules are sourced from "Shopee Official Terms" (Help Center Article 73111 & Program Terms).
 * - Tax rules are sourced from "DJP Official" (UU HPP No. 7/2021, PP No. 55/2022, PMK 164/2023, PMK 37/2025).
 * - Supported Shopee Category-dependent Rates: 10.00%, 9.50%, 9.00%, 8.25%, 6.75%, 6.50%, 5.25%, 4.25%, 2.50%, 0.00%.
 * - Rule versioning is supported via effectiveFrom and effectiveUntil.
 */

// 1. ORDER PROCESSING FEE (Biaya Layanan Pemrosesan Pesanan)
// Fixed Rp1.250 per completed order, effective since 2024-09-01
export const OFFICIAL_ORDER_PROCESSING_FEE_RULE: MarketplaceFeeRule = {
  id: 'rule_proc_001',
  marketplace: 'SHOPEE',
  sellerType: 'NON_STAR',
  category: 'Umum',
  feeType: 'PROCESSING',
  percentage: 0,
  fixedFee: 1250, // Rp 1.250 flat per pesanan selesai (Bukan persentase)
  calculationBase: 'NET_SALES',
  effectiveFrom: '2024-09-01',
  effectiveUntil: undefined,
  active: true,
  status: 'ACTIVE',
  source: 'Shopee Official Terms',
  sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
  notes: 'Dikenakan flat Rp1.250 per pesanan selesai di Shopee Indonesia. Tidak pernah dihitung sebagai persentase.',
  verifiedAt: '2026-09-25',
  taxIncluded: true,
  taxType: 'NONE',
  taxRate: 0,
};

// 2. MARKETPLACE ADMINISTRATION FEE RULES
// Sourced from Shopee Official Terms (Article 73111 - Biaya Administrasi Shopee)
// Documented rates: 10.00%, 9.50%, 9.00%, 8.25%, 6.75%, 6.50%, 5.25%, 4.25%, 2.50%, 0.00%
export const INITIAL_MARKETPLACE_FEE_RULES: MarketplaceFeeRule[] = [
  // Special Non-Star 0% Rule (Produk diunggah sebelum 1 Agustus 2026, pesanan selesai <= 50)
  {
    id: 'fee_shopee_nonstar_first_products_grace',
    marketplace: 'SHOPEE',
    sellerType: 'NON_STAR',
    category: 'Umum',
    feeType: 'ADMINISTRATION',
    percentage: 0.0,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2023-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: '0.00% Admin Fee untuk toko Non-Star yang memenuhi syarat pesanan selesai <= 50 dan produk diunggah sebelum batas 1 Agustus 2026.',
    verifiedAt: '2026-09-25',
    specialEligibility: 'FIRST_PRODUCTS_BEFORE_AUG_2026',
    taxIncluded: true,
  },

  // Fashion & Pakaian (Kategori A)
  {
    id: 'fee_shopee_fsh_nonstar',
    marketplace: 'SHOPEE',
    sellerType: 'NON_STAR',
    category: 'Fashion & Pakaian',
    feeType: 'ADMINISTRATION',
    percentage: 6.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori A Fashion & Pakaian Non-Star reguler (6.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_fsh_star',
    marketplace: 'SHOPEE',
    sellerType: 'STAR',
    category: 'Fashion & Pakaian',
    feeType: 'ADMINISTRATION',
    percentage: 8.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori A Fashion & Pakaian Star Seller resmi (8.25%). Bukan legacy 7.5%.',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_fsh_starplus',
    marketplace: 'SHOPEE',
    sellerType: 'STAR_PLUS',
    category: 'Fashion & Pakaian',
    feeType: 'ADMINISTRATION',
    percentage: 8.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori A Fashion & Pakaian Star+ Seller resmi (8.25%). Bukan legacy 8.5%.',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_fsh_mall',
    marketplace: 'SHOPEE',
    sellerType: 'MALL',
    category: 'Fashion & Pakaian',
    feeType: 'ADMINISTRATION',
    percentage: 10.0,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori A Fashion Shopee Mall Official Brand (10.00%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },

  // Kecantikan & Perawatan (Kategori A FMCG Beauty)
  {
    id: 'fee_shopee_bty_nonstar',
    marketplace: 'SHOPEE',
    sellerType: 'NON_STAR',
    category: 'Kecantikan & Perawatan',
    feeType: 'ADMINISTRATION',
    percentage: 6.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori A Beauty & Skincare Non-Star reguler (6.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_bty_star',
    marketplace: 'SHOPEE',
    sellerType: 'STAR',
    category: 'Kecantikan & Perawatan',
    feeType: 'ADMINISTRATION',
    percentage: 8.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori A Beauty & Skincare Star Seller resmi (8.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_bty_starplus',
    marketplace: 'SHOPEE',
    sellerType: 'STAR_PLUS',
    category: 'Kecantikan & Perawatan',
    feeType: 'ADMINISTRATION',
    percentage: 8.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori A Beauty & Skincare Star+ Seller resmi (8.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_bty_mall',
    marketplace: 'SHOPEE',
    sellerType: 'MALL',
    category: 'Kecantikan & Perawatan',
    feeType: 'ADMINISTRATION',
    percentage: 9.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori A Beauty Shopee Mall Official Brand (9.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },

  // Elektronik & Gadget (Kategori B - Audio, Konsol, Kamera, Drone)
  {
    id: 'fee_shopee_elc_nonstar',
    marketplace: 'SHOPEE',
    sellerType: 'NON_STAR',
    category: 'Elektronik & Gadget',
    feeType: 'ADMINISTRATION',
    percentage: 6.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori B Elektronik & Gadget Non-Star reguler (6.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_elc_star',
    marketplace: 'SHOPEE',
    sellerType: 'STAR',
    category: 'Elektronik & Gadget',
    feeType: 'ADMINISTRATION',
    percentage: 6.75,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori B Elektronik & Gadget Star Seller resmi (6.75%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_elc_starplus',
    marketplace: 'SHOPEE',
    sellerType: 'STAR_PLUS',
    category: 'Elektronik & Gadget',
    feeType: 'ADMINISTRATION',
    percentage: 6.75,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori B Elektronik & Gadget Star+ Seller resmi (6.75%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_elc_mall',
    marketplace: 'SHOPEE',
    sellerType: 'MALL',
    category: 'Elektronik & Gadget',
    feeType: 'ADMINISTRATION',
    percentage: 9.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori B Elektronik Shopee Mall Official Brand (9.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },

  // Komputer & Smartphone (Kategori C - High-End Electronics)
  {
    id: 'fee_shopee_cpc_nonstar',
    marketplace: 'SHOPEE',
    sellerType: 'NON_STAR',
    category: 'Komputer & Smartphone',
    feeType: 'ADMINISTRATION',
    percentage: 4.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori C High-End Komputer & Smartphone Non-Star (4.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_cpc_star',
    marketplace: 'SHOPEE',
    sellerType: 'STAR',
    category: 'Komputer & Smartphone',
    feeType: 'ADMINISTRATION',
    percentage: 5.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori C High-End Komputer & Smartphone Star Seller (5.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_cpc_starplus',
    marketplace: 'SHOPEE',
    sellerType: 'STAR_PLUS',
    category: 'Komputer & Smartphone',
    feeType: 'ADMINISTRATION',
    percentage: 5.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori C High-End Komputer & Smartphone Star+ (5.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_cpc_mall',
    marketplace: 'SHOPEE',
    sellerType: 'MALL',
    category: 'Komputer & Smartphone',
    feeType: 'ADMINISTRATION',
    percentage: 9.0,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori C High-End Shopee Mall (9.00%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },

  // Logam Mulia & Perhiasan (Kategori D)
  {
    id: 'fee_shopee_jwl_nonstar',
    marketplace: 'SHOPEE',
    sellerType: 'NON_STAR',
    category: 'Logam Mulia & Perhiasan',
    feeType: 'ADMINISTRATION',
    percentage: 4.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori D Logam Mulia & Perhiasan Berharga Non-Star (4.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_jwl_star',
    marketplace: 'SHOPEE',
    sellerType: 'STAR',
    category: 'Logam Mulia & Perhiasan',
    feeType: 'ADMINISTRATION',
    percentage: 4.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori D Logam Mulia & Perhiasan Berharga Star Seller (4.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_jwl_mall',
    marketplace: 'SHOPEE',
    sellerType: 'MALL',
    category: 'Logam Mulia & Perhiasan',
    feeType: 'ADMINISTRATION',
    percentage: 8.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori D Logam Mulia Shopee Mall (8.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },

  // Sembako & Kebutuhan Pokok (Kategori E - Rendah Margin)
  {
    id: 'fee_shopee_smb_nonstar',
    marketplace: 'SHOPEE',
    sellerType: 'NON_STAR',
    category: 'Sembako & Kebutuhan Pokok',
    feeType: 'ADMINISTRATION',
    percentage: 2.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori E Sembako & Komoditas Pokok Non-Star (2.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_low_margin',
    marketplace: 'SHOPEE',
    sellerType: 'STAR',
    category: 'Sembako & Kebutuhan Pokok',
    feeType: 'ADMINISTRATION',
    percentage: 2.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori E Sembako & Komoditas Pokok Star Seller resmi (2.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_smb_starplus',
    marketplace: 'SHOPEE',
    sellerType: 'STAR_PLUS',
    category: 'Sembako & Kebutuhan Pokok',
    feeType: 'ADMINISTRATION',
    percentage: 2.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori E Sembako Star+ Seller resmi (2.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_smb_mall',
    marketplace: 'SHOPEE',
    sellerType: 'MALL',
    category: 'Sembako & Kebutuhan Pokok',
    feeType: 'ADMINISTRATION',
    percentage: 2.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori E Sembako Shopee Mall (2.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },

  // Kategori Umum
  {
    id: 'fee_shopee_gen_nonstar',
    marketplace: 'SHOPEE',
    sellerType: 'NON_STAR',
    category: 'Umum',
    feeType: 'ADMINISTRATION',
    percentage: 6.5,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori umum Non-Star Seller reguler (6.50%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_gen_star',
    marketplace: 'SHOPEE',
    sellerType: 'STAR',
    category: 'Umum',
    feeType: 'ADMINISTRATION',
    percentage: 8.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori umum Star Seller resmi (8.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_gen_starplus',
    marketplace: 'SHOPEE',
    sellerType: 'STAR_PLUS',
    category: 'Umum',
    feeType: 'ADMINISTRATION',
    percentage: 8.25,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Kategori umum Star+ Seller resmi (8.25%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'fee_shopee_gen_mall',
    marketplace: 'SHOPEE',
    sellerType: 'MALL',
    category: 'Umum',
    feeType: 'ADMINISTRATION',
    percentage: 9.0,
    fixedFee: 0,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    active: true,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Shopee Mall Umum (9.00%).',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
];

// 3. SELLER PROGRAM RULES
// Sourced from Shopee Official Terms
export const INITIAL_PROGRAM_RULES: SellerProgramRule[] = [
  {
    id: 'prog_fs_xtra',
    code: 'FREE_SHIPPING_XTRA',
    name: 'Gratis Ongkir XTRA',
    description: 'Program badge Gratis Ongkir Xtra Shopee untuk meningkatkan konversi checkout pembeli.',
    enabled: true,
    rate: 4.0, // 4.0%
    cap: 40000, // Resmi: Rp 40.000 (reguler)
    specialSizeCap: 60000, // Resmi: Rp 60.000 (produk ukuran khusus)
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    categoryRules: {
      'Fashion & Pakaian': { rate: 4.0, cap: 40000, specialSizeCap: 60000 },
      'Elektronik & Gadget': { rate: 3.5, cap: 40000, specialSizeCap: 60000 },
      'Komputer & Smartphone': { rate: 3.5, cap: 40000, specialSizeCap: 60000 },
      'Kecantikan & Perawatan': { rate: 4.0, cap: 40000, specialSizeCap: 60000 },
      'Umum': { rate: 4.0, cap: 40000, specialSizeCap: 60000 },
    },
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Batas cap maksimal Rp40.000 untuk barang reguler dan Rp60.000 untuk produk berukuran khusus.',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'prog_promo_xtra',
    code: 'PROMO_XTRA',
    name: 'Promo XTRA (Cashback XTRA)',
    description: 'Program voucher cashback koin xtra Shopee untuk pembeli toko Anda.',
    enabled: true,
    rate: 4.5, // Resmi: 4.5%
    cap: 60000, // Resmi: Maksimal Rp 60.000 per kuantitas
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    categoryRules: {
      'Fashion & Pakaian': { rate: 4.5, cap: 60000 },
      'Elektronik & Gadget': { rate: 3.0, cap: 50000 },
      'Komputer & Smartphone': { rate: 3.0, cap: 50000 },
      'Kecantikan & Perawatan': { rate: 4.5, cap: 60000 },
      'Umum': { rate: 4.5, cap: 60000 },
    },
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Tarif program 4.5% dengan batas cap maksimal Rp60.000 per kuantitas.',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'prog_promo_xtra_plus',
    code: 'PROMO_XTRA_PLUS',
    name: 'Promo XTRA+ (Double Boost)',
    description: 'Program bundling gabungan Gratis Ongkir Xtra + Cashback Xtra. Tarif sudah termasuk PPN.',
    enabled: true,
    rate: 6.5, // Resmi: 6.5%
    cap: 80000, // Resmi: Maksimal Rp 80.000 per kuantitas
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-06-01',
    effectiveUntil: undefined,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Tarif program bundling 6.5% dengan cap maksimal Rp80.000 per kuantitas. Metadata taxIncluded bernilai true; angka fee 6.5% sudah mencakup perlakuan PPN (tax-inclusive) sesuai ketentuan resmi Shopee.',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
    taxType: 'PPN',
    taxRate: 11,
  },
  {
    id: 'prog_pre_order',
    code: 'PRE_ORDER',
    name: 'Biaya Layanan Pre-Order',
    description: 'Biaya layanan tambahan untuk produk yang dibuat berdasarkan pesanan (SLA PO > 7 hari).',
    enabled: true,
    rate: 3.0, // Resmi: 3.0% per kuantitas untuk kategori tertentu
    cap: undefined,
    calculationBase: 'AFTER_SELLER_DISCOUNT_AND_VOUCHER',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://help.shopee.co.id/portal/article/73111',
    notes: 'Biaya 3.0% dikenakan pada produk pre-order dengan waktu pengemasan (DTS) > 7 hari.',
    verifiedAt: '2026-09-25',
    taxIncluded: true,
  },
  {
    id: 'prog_affiliate',
    code: 'AFFILIATE',
    name: 'Shopee Affiliate Seller Commission',
    description: 'Komisi affiliasi untuk kreator Shopee Video & Live. Basis Nilai Pembelian Selesai Bersih.',
    enabled: false,
    rate: 5.0, // Default konfigurasi seller
    cap: undefined,
    calculationBase: 'NET_COMPLETED_PURCHASE_VALUE',
    effectiveFrom: '2024-01-01',
    effectiveUntil: undefined,
    status: 'ACTIVE',
    source: 'Shopee Official Terms',
    sourceUrl: 'https://affiliate.shopee.co.id',
    notes: 'Basis komisi dihitung dari Net Completed Purchase Value. PPN dihitung terpisah sesuai configured tax rule UU HPP.',
    verifiedAt: '2026-09-25',
    taxIncluded: false,
    taxType: 'PPN',
    taxRate: 11,
  },
];

// 4. OFFICIAL PPN TAX RULE (UU Harmonisasi Peraturan Perpajakan No. 7/2021)
export const OFFICIAL_PPN_TAX_RULE: TaxRule = {
  id: 'tax_ppn_11',
  name: 'Pajak Pertambahan Nilai (PPN)',
  taxpayerType: 'Company',
  taxScheme: 'Other',
  taxType: 'PPN',
  taxRate: 11, // Persentase tarif efektif yang berlaku saat ini
  headlineRate: 11, // Statutory headline rate sesuai UU HPP No. 7/2021 Pasal 7
  effectiveRate: 11, // Effective rate yang aktif diimplementasikan
  rate: 11,
  taxBase: 'NET_COMPLETED_PURCHASE_VALUE',
  taxBaseType: 'NET_COMPLETED_PURCHASE_VALUE',
  taxIncluded: false,
  annualNonTaxableThreshold: 0,
  pkpThreshold: 4800000000,
  withholdingRate: 11,
  regulationNumber: 'UU No. 7 Tahun 2021 (UU HPP)',
  source: 'DJP Official',
  sourceUrl: 'https://pajak.go.id/id/uu-harmonisasi-peraturan-perpajakan',
  notes: 'Tarif PPN sebesar 11% (effective rate) berdasarkan UU No. 7/2021 (UU HPP) berlaku mulai 1 April 2022 atas komisi jasa perantara/afiliasi Shopee. Statutory headline rate diatur dalam Pasal 7 UU HPP.',
  effectiveFrom: '2022-04-01',
  effectiveUntil: undefined,
  status: 'ACTIVE',
  verifiedAt: '2026-09-25',
};

// 5. TAX RULES (PP 55/2022 & PMK 164/2023)
export const OFFICIAL_TAX_RULES: TaxRule[] = [
  {
    id: 'tax_umkm_pp55',
    name: 'PPh Final UMKM 0.5% (PP 55/2022)',
    taxpayerType: 'Individual',
    taxScheme: 'UMKM Final',
    taxType: 'PPH_FINAL_UMKM',
    taxRate: 0.5,
    headlineRate: 0.5,
    effectiveRate: 0.5,
    rate: 0.5,
    taxBase: 'NET_SALES',
    taxBaseType: 'NET_SALES',
    taxIncluded: false,
    annualNonTaxableThreshold: 500000000, // Rp 500 Juta per tahun untuk WPOP UMKM bebas pajak
    pkpThreshold: 4800000000, // Rp 4.8 Miliar per tahun batas PKP
    withholdingRate: 0.5,
    regulationNumber: 'PP No. 55 Tahun 2022 Pasal 56-57 & PMK No. 164/PMK.03/2023',
    source: 'DJP Official',
    sourceUrl: 'https://pajak.go.id/id/peraturan/pp-nomor-55-tahun-2022',
    notes: 'PPh Final 0.5% peredaran bruto untuk WPOP UMKM dengan batas omzet tidak kena pajak Rp500 Juta/tahun. Jangka waktu pemanfaatan maksimal 7 tahun.',
    effectiveFrom: '2022-12-20',
    effectiveUntil: undefined,
    status: 'ACTIVE',
    verifiedAt: '2026-09-25',
  },
  {
    id: 'tax_badan_pp55',
    name: 'PPh Final Badan PT/CV 0.5%',
    taxpayerType: 'Company',
    taxScheme: 'UMKM Final',
    taxType: 'PPH_FINAL_UMKM',
    taxRate: 0.5,
    headlineRate: 0.5,
    effectiveRate: 0.5,
    rate: 0.5,
    taxBase: 'NET_SALES',
    taxBaseType: 'NET_SALES',
    taxIncluded: false,
    annualNonTaxableThreshold: 0, // Badan tidak mendapat batas Rp 500jt bebas pajak
    pkpThreshold: 4800000000,
    withholdingRate: 0.5,
    regulationNumber: 'PP No. 55 Tahun 2022 Pasal 56-59',
    source: 'DJP Official',
    sourceUrl: 'https://pajak.go.id/id/peraturan/pp-nomor-55-tahun-2022',
    notes: 'PPh Final 0.5% untuk Wajib Pajak Badan UMKM (PT/CV/Koperasi) dengan omzet <= Rp 4.8 Miliar. Dikenakan sejak rupiah pertama. Jangka waktu pemanfaatan: 4 tahun (CV/Koperasi) atau 3 tahun (PT) sejak terdaftar.',
    effectiveFrom: '2022-12-20',
    effectiveUntil: undefined,
    status: 'ACTIVE',
    verifiedAt: '2026-09-25',
  },
];

// 6. OFFICIAL PPh 22 MARKETPLACE RULE (PMK 37/2025)
// Effective from 2026-11-01 (1 November 2026)
export const OFFICIAL_PPH22_RULE: Pph22Rule = {
  id: 'rule_pph22_pmk37_2025',
  name: 'PPh Pasal 22 Marketplace (PMK 37/2025)',
  rate: 0.5, // 0.5%
  calculationBase: 'NET_SALES',
  effectiveFrom: '2026-11-01', // Effective 1 November 2026
  effectiveUntil: undefined,
  regulation: 'Peraturan Menteri Keuangan No. 37 Tahun 2025',
  source: 'DJP Official',
  sourceUrl: 'https://pajak.go.id/id/peraturan/pmk-37-2025',
  notes: 'Withholding PPh 22 sebesar 0.5% dipungut oleh marketplace atas transaksi mulai 1 November 2026. Dasar pengenaan adalah peredaran usaha bruto tidak termasuk PPN dan PPnBM.',
  verifiedAt: '2026-09-25',
  status: 'ACTIVE',
};
